"""empty message

Revision ID: 27b5c9a19cac
Revises: 50b6fe5b5e4a
Create Date: 2020-05-23 18:57:24.755489

"""
from alembic import op
import sqlalchemy as sa
from main.migration_types import *


# revision identifiers, used by Alembic.
revision = '27b5c9a19cac'
down_revision = '50b6fe5b5e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_word',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_word')
    op.drop_table('word')
    op.drop_table('document')
    # ### end Alembic commands ###
