version: 1

formatters:
  simple:
    format: '%(asctime)s %(levelname)5s %(threadName)s %(name)s:%(lineno)d: - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ${PROJ_HOME}/webapp/log/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ${PROJ_HOME}/webapp/log/error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  werkzeug:
    level: DEBUG
  main:
    level: DEBUG

root:
  level: DEBUG
  handlers: [console, debug_file_handler, error_file_handler]
  propagate: yes